name: PR checkstyle
on:
  workflow_dispatch:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]

jobs:
  lint:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./odd_collector_gcp"
          args: "format --check --diff"
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./odd_collector_gcp"
          args: "check"
