name: PR checkstyle
on:
  workflow_dispatch:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]

jobs:
  lint:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./odd_collector_gcp"
          version: "22.3.0"